security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        db_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: db_provider
            form_login:
                default_target_path: display_user
                login_path: app_login
                check_path: app_login
                success_handler: App\Controller\CustomAuthenticationSuccessHandler

            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%env(APP_SECRET)%'

    access_control:
    - { path: ^/home, roles: ROLE_USER } 
    - { path: ^/user, roles: ROLE_ADMIN } 
    


